### ISSUE TITLE
Improve backtrace on errors (opt-out of implicit exception chaining?)

### ISSUE THREAD

**Issue by rohanpm** [rohanpm/more-executors#173]
Under some circumstances, it seems like we generate a useless/confusing chained exception of the form:

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/more_executors/_impl/common.py", line 94, in copy_exception
 future.set_exception_info(exception, traceback)
 File "/usr/local/lib/python3.7/site-packages/more_executors/_impl/map.py", line 83, in set_exception_info
 super(MapFuture, self).set_exception_info(exception, traceback)
AttributeError: 'super' object has no attribute 'set_exception_info'
During handling of the above exception, another exception occurred:
(...)
<the real exception raised by the future>
```

It would be best to avoid this.  I believe the problem is that we're calling set_exception_info (which is Python2-only) and catching exceptions for the Python3 case, but the exception ends up leaked anyway due to implicit exception chaining.

I have vague memories of already trying to handle this, so have a look in history before working on this.

**Comment by rohanpm** [comment]
This seems to be a duplicate of #162.  Based on the line numbers in the error, the user must have been using a library version older than v2.4.0 where the fix was made.
